### PR TITLE
Update control-plane-ips-wdc.txt

### PR DESCRIPTION
**Pull request by ranum**
Add ip address to whitelist for ingress heathcheck

### CODE REVIEW

**Comment by bradbehle** [comment]
What is the background for this change?

**Comment by ranum** [comment]
Thank you for responding.  Our kubernetes cluster shows a "warning" for the ingress status.  After many weeks of back and forth with support, they responded with the solution posted below.  So, I simply followed those instructions from support and added the IP address that was giving the timeout to the whitelist.  

********
Hello DAVID  

"They suspect that you must have a packet filter somewhere, and we are unable to access your ingress controller.

$ curl https://albhealth.health-patterns-1-dcc48c44d831198cb8496b1ec68d7d12-0000.us-east.containers.appdomain.cloud -v --connect-timeout 3

* Trying 150.239.84.92:443...

* TCP_NODELAY set

* After 1498ms connect time, move on!

* connect to 150.239.84.92 port 443 failed: Connection timed out

* Trying 169.63.179.154:443...

* TCP_NODELAY set

* After 747ms connect time, move on!

* connect to 169.63.179.154 port 443 failed: Connection timed out

* Failed to connect to albhealth.health-patterns-1-dcc48c44d831198cb8496b1ec68d7d12-0000.us-east.containers.appdomain.cloud port 443: Connection timed out

* Closing connection 0

curl: (28) Failed to connect to albhealth.health-patterns-1-dcc48c44d831198cb8496b1ec68d7d12-0000.us-east.containers.appdomain.cloud port 443: Connection timed out



So, once you whitelist the control plane IPs (https://github.com/IBM-Cloud/kube-samples/blob/master/control-plane-ips/control-plane-ips-wdc.txt) and our management service will be able to query the albhealth.health-patterns-1-dcc48c44d831198cb8496b1ec68d7d12-0000.us-east.containers.appdomain.cloud endpoint, the warnings will probably go away. "



Best regards,

Bogdan C.

VPC & Compute Support Engineer

IBM Cloud Technical Support
********

**Comment by bradbehle** [comment]
Can you send me the ticket ID so I can look up the ticket and try to understand what is going on?

**Comment by bradbehle** [comment]
I read through the ticket and there was just a misunderstanding.  Let's handle the rest of this through the customer ticket, but the summary is that the support person was recommending in the ticket that in whatever firewall/security group/ACL that you have on your LoadBalancer, you need to allow all the CIDRs that are in https://github.com/IBM-Cloud/kube-samples/blob/master/control-plane-ips/control-plane-ips-wdc.txt (not update control-plane-ips-wdc.txt).

**Comment by bradbehle** [comment]
Because it might take a bit of time for the support ticket to be updated, here's what I put in there:

The Ingress for your cluster (which is a LBaaS instance in your account with IPs 150.239.84.92 and 169.63.179.154) appears to have some kind of security group, ACL, and/or firewall rules on it that is rejecting most traffic. When we try to ping or connect to these IPs, the packets are just getting dropped, we get no responses. The suggestion is that whatever security group, ACL, and/or firewall rules that you have, you need to allow all the IPs/CIDRs that are in https://github.com/IBM-Cloud/kube-samples/blob/master/control-plane-ips/control-plane-ips-wdc.txt

I closed this PR since it isn't the right way to fix the problem you are having

**Pull request closed without merging**
