### PR TITLE
rm empty v3 dir & update pols

### PR DESCRIPTION
**Pull request by derekpoindexter**
removes the empty v3 dir & updates the policies

### CODE REVIEW

**Review by bradbehle — CHANGES_REQUESTED** [review]
In general I think this change is great.  I do have a few concerns about it though
1. We might have customers with automation that are taking at least some of these calico policies as-is and applying them to production cluster, so removing the `calico-v3` (as annoying as it is) might break that automation.  We don't have any good way to ensure we notify customers of possibly breaking changes.   Maybe we could post a change to the README.md in this repo and merge that right away saying that this change is coming, and then also post a notification in slack in #armada-users, #armada-vpc-users, and #iks-openshift-users saying that this path change (breaking change) is coming?  Then wait a few weeks to merge the path change part?   That would at least give groups that monitor this repo for changes or those slack channels a chance to prepare or tell us if we will break them
2. Can you (if you haven't already), just do a sanity check to make sure the IPs in these lists match what we have in the docs now?

**Comment by derekpoindexter** [comment]
@bradbehle 
for 1 - I have a PR to update the readme #197 and posted in the user channels.
for 2 - I've cross-checked the IPs in this PR and they match what we have in docs.

**Comment by bradbehle** [comment]
@derekpoindexter Thanks.  I just merged https://github.com/IBM-Cloud/kube-samples/pull/197   And it turns out there is at least one customer that would have been broken by this: https://ibm-argonauts.slack.com/archives/C4S4NUCB1/p1651897616345189?thread_ts=1651848056.538839&cid=C4S4NUCB1, so thanks for posting so quickly

**Comment by derekpoindexter** [comment]
@bradbehle I think we can merge this one now

**Review by bradbehle — APPROVED** [review]

**Pull request merged**
